plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - COMPARISION.md
  - README.md
  - LICENSE.md
  - INSTALL_UBUNTU_ON_MAC.md
  # - CODE_OF_CONDUCT.md
  # - CONTRIBUTING.md
  # - ISSUE_TEMPLATE.md
  # - PULL_REQUEST_TEMPLATE.md